### ISSUE TITLE
Cant use update() on model trained with recipes

### ISSUE THREAD

**Issue by BU-1** [topepo/caret#1021]
I'm having an issue using `update.train` when I train models using a recipe. I'm not having any issues when I train without a recipe:
```{R}
library(caret)
data(iris)
TrainData <- iris[,1:4]
TrainClasses <- iris[,5]
set.seed(1)
knnFit1 <- train(TrainData, TrainClasses,
                 method = "knn",
                 preProcess = c("center", "scale"),
                 tuneLength = 10,
                 trControl = trainControl(method = "cv")
                 )
knnFit1$bestTune #k = 13
knnFit1_updated = update(knnFit1, list(.k = 3)) #set k = 3
knnFit1_updated$bestTune #k = 3, model was updated
```

However, when I train with a recipe:
```{R}
TrainDataWithOutcome <- iris[,1:5]
#Make pre-processing recipe
library(recipes)
iris_recipe = (recipe(Species ~ ., data = TrainDataWithOutcome) 
               %>% step_center(all_predictors())
               %>% step_scale(all_predictors())
               )
set.seed(1)
knn_recipe <- train(iris_recipe, 
                    TrainDataWithOutcome,
                    method = "knn",
                    tuneLength = 10,
                    trControl = trainControl(method = "cv")
                    )
knn_recipe$bestTune #k = 13
update(knn_recipe,list(.k = 3)) #error
```
I receive an error that states: 
` Error in knnreg.matrix(as.matrix(x), y, k = param$k, ...) : y must be numeric `

```{R}
>sessionInfo()

R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2.2  recipes_0.1.4   dplyr_0.7.8     caret_6.0-81    ggplot2_3.1.0   lattice_0.20-38

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0         gower_0.1.2        pillar_1.3.1       compiler_3.5.1     plyr_1.8.4         bindr_0.1.1        class_7.3-14       iterators_1.0.10   tools_3.5.1       
[10] rpart_4.1-13       ipred_0.9-8        lubridate_1.7.4    tibble_1.4.2       gtable_0.2.0       nlme_3.1-137       pkgconfig_2.0.2    rlang_0.3.0.1      Matrix_1.2-15     
[19] foreach_1.4.4      rstudioapi_0.8     yaml_2.2.0         prodlim_2018.04.18 e1071_1.7-0        withr_2.1.2        stringr_1.3.1      generics_0.0.2     stats4_3.5.1      
[28] nnet_7.3-12        grid_3.5.1         tidyselect_0.2.5   glue_1.3.0         data.table_1.11.8  R6_2.3.0           survival_2.43-3    lava_1.6.4         tidyr_0.8.2       
[37] purrr_0.2.5        reshape2_1.4.3     magrittr_1.5       splines_3.5.1      MASS_7.3-51.1      scales_1.0.0       codetools_0.2-15   ModelMetrics_1.2.2 assertthat_0.2.0  
[46] timeDate_3043.102  colorspace_1.3-2   stringi_1.2.4      lazyeval_0.2.1     munsell_0.5.0      crayon_1.3.4
```

**Comment by topepo** [comment]
This should fix it but please comment/reopen if it does not.

**Comment by BU-1** [comment]
@topepo looks like it's working, thank you! Huge help!

**Comment by BU-1** [comment]
@topepo Still having issues with `method = "xgbTree"`.

This section below works fine (without a recipe) 

```{R}
#Train model without recipe (no issues)
library(caret)
data(iris)
TrainData = iris[,1:4]
TrainClasses = iris[,5]
set.seed(1)
xgbTreeModel = train(TrainData, TrainClasses,
                 method = "xgbTree",
                 preProcess = c("center", "scale"),
                 tuneLength = 1,
                 trControl = trainControl(method = "cv")
                 )

xgbTreeModel$bestTune
new_tune = xgbTreeModel$results[4,1:7]
xgbTreeModel = update(xgbTreeModel, new_tune)
xgbTreeModel$bestTune
```

But when I train with a recipe...
```{R}
#Repeat with a recipe
TrainDataWithOutcome = iris[,1:5]
#Make pre-processing recipe
library(recipes)
iris_recipe = (recipe(Species ~ ., data = TrainDataWithOutcome) 
               %>% step_center(all_predictors())
               %>% step_scale(all_predictors())
               )
set.seed(1)
xgb_recipe <- train(iris_recipe, 
                    TrainDataWithOutcome,
                    method = "xgbTree",
                    tuneLength = 1,
                    trControl = trainControl(method = "cv")
                    )
xgb_recipe$bestTune
new_recipe_tune = xgb_recipe$results[4,1:7]
update(xgb_recipe, new_recipe_tune) #error
```

I get this error:
```{R}
 Error in check.booster.params(params, ...) : 
  'num_class' > 1 parameter must be set for multiclass classification 
```


```{R}
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] plyr_1.8.4      xgboost_0.71.2  recipes_0.1.5   dplyr_0.8.0.1   caret_6.0-82    ggplot2_3.1.0   lattice_0.20-38

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1         pillar_1.3.1       compiler_3.5.1     gower_0.2.0        iterators_1.0.10   class_7.3-14       tools_3.5.1        rpart_4.1-13       ipred_0.9-8       
[10] lubridate_1.7.4    tibble_2.1.1       gtable_0.2.0       nlme_3.1-137       pkgconfig_2.0.2    rlang_0.3.2        Matrix_1.2-15      foreach_1.4.4      rstudioapi_0.8    
[19] yaml_2.2.0         prodlim_2018.04.18 e1071_1.7-0        stringr_1.4.0      withr_2.1.2        generics_0.0.2     stats4_3.5.1       nnet_7.3-12        grid_3.5.1        
[28] tidyselect_0.2.5   data.table_1.12.0  glue_1.3.1         R6_2.4.0           survival_2.43-3    lava_1.6.5         tidyr_0.8.3        reshape2_1.4.3     purrr_0.3.2       
[37] magrittr_1.5       ModelMetrics_1.2.2 splines_3.5.1      scales_1.0.0       codetools_0.2-15   MASS_7.3-51.1      assertthat_0.2.1   timeDate_3043.102  colorspace_1.4-1  
[46] stringi_1.4.3      lazyeval_0.2.2     munsell_0.5.0      crayon_1.3.4
```
