### ISSUE TITLE
Error "All RMSE values missing" while training with SBC method in frbs package using Caret

### ISSUE THREAD

**Issue by snair1591** [topepo/caret#539]
I've asked this question in Stackoverflow yesterday and got couple of responses but none worked for me, (link: [http://stackoverflow.com/questions/40838476/error-something-is-wrong-all-the-rmse-metric-values-are-missing-using-sbc-fro](url))

I am providing a reproducible code using iris dataset:
`library(caret)
library(pROC)
data(iris)

dat <- iris[,1:4]
grid<-expand.grid(r.a = c(0.5), eps.high = c(0.5), eps.low = c(0))
gbmFi <- train(Sepal.Length ~ ., data = dat, method = "SBC", 
                     tuneGrid=grid, verbose = FALSE)
gbmFi$results`

and this pops the error:

`Something is wrong; all the RMSE metric values are missing:
      RMSE        Rsquared  
 Min.   : NA   Min.   : NA  
 1st Qu.: NA   1st Qu.: NA  
 Median : NA   Median : NA  
 Mean   :NaN   Mean   :NaN  
 3rd Qu.: NA   3rd Qu.: NA  
 Max.   : NA   Max.   : NA  
 NA's   :1     NA's   :1    
Error in train.default(x, y, weights = w, ...) : Stopping
In addition: There were 26 warnings (use warnings() to see them)
`
Warning message looks like this:
`25: In eval(expr, envir, enclos) :
  model fit failed for Resample25: r.a=0.5, eps.high=0.5, eps.low=0 Error in frbs.learn(data.train = structure(c(3, 3.2, 3.2, 3.1, 3.1, 3.6,  : 
  unused arguments (r.a = 0.5, eps.high = 0.5, eps.low = 0, range.data.ori = c(2.115, 3.985, 0.82, 6.98, -0.02, 2.62, 4.12, 8.08), verbose = FALSE)`

Please note that:
1. None of the variables are of class factor.
2. I've installed and updated all required packages (caret, frbs, ggplot2, lattice, etc..)

Strangest thing is same code works in my colleague's system. Am I missing something? Any help or suggestion to fix this issue would be much appreciated. Thanks in advance.

**Comment by JackStat** [comment]
Can you share your `session_info`?

**Comment by snair1591** [comment]
Hi, this is the sessionInfo()
`> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] frbs_3.1-0      pROC_1.8        caret_6.0-73    ggplot2_2.2.0   lattice_0.20-34

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7        magrittr_1.5       splines_3.3.2      MASS_7.3-45        munsell_0.4.3     
 [6] colorspace_1.3-0   foreach_1.4.3      minqa_1.2.4        stringr_1.1.0      car_2.1-3         
[11] plyr_1.8.4         tools_3.3.2        parallel_3.3.2     nnet_7.3-12        pbkrtest_0.4-6    
[16] grid_3.3.2         gtable_0.2.0       nlme_3.1-128       mgcv_1.8-15        quantreg_5.29     
[21] MatrixModels_0.4-1 iterators_1.0.8    lme4_1.1-12        lazyeval_0.2.0     assertthat_0.1    
[26] tibble_1.2         Matrix_1.2-7.1     nloptr_1.0.4       reshape2_1.4.2     ModelMetrics_1.1.0
[31] codetools_0.2-15   stringi_1.1.2      compiler_3.3.2     scales_0.4.1       stats4_3.3.2      
[36] SparseM_1.74      `

**Comment by topepo** [comment]
I fixed a bug that should solve the issue. 

However, note that `verbose` isn't an argument so take that out.

**Comment by snair1591** [comment]
Thanks Max for looking into this issue. I tried again, first after updating the packages and then removed & reinstalled (both caret and frbs) the packages. Am still getting the error. Should I copy the 'SBC.R' file to somewhere?
Also, remark regarding 'verbose' argument noted. Will run without it.

**Comment by topepo** [comment]
You can download the [file](https://github.com/topepo/caret/blob/master/models/files/SBC.R) locally, source it, then use
```r
dat <- iris[,1:4]
grid<-expand.grid(r.a = c(0.5), eps.high = c(0.5), eps.low = c(0))
gbmFi <- train(Sepal.Length ~ ., data = dat, 
               method = modelInfo, # <- contained in SBC.R
               tuneGrid=grid)
```

**Comment by snair1591** [comment]
Thanks a lot Max!!! That did the trick. Really appreciate your effort. Cheers!
