### ISSUE TITLE
NA name in multiClassSummary

### ISSUE THREAD

**Issue by topepo** [topepo/caret#564]
```r
> library(caret)
Loading required package: lattice
Loading required package: ggplot2
> classes <- c("class1", "class2", "class3")
> set.seed(1)
> dat <- data.frame(obs =  factor(sample(classes, 50, replace = TRUE)),
+                   pred = factor(sample(classes, 50, replace = TRUE)),
+                   class1 = runif(50), class2 = runif(50), class3 = runif(50))
> multiClassSummary(dat, lev = classes)
                  <NA>               Mean_AUC               Accuracy                  Kappa 
                    NA             0.61483682             0.38000000             0.06344411 
      Mean_Sensitivity       Mean_Specificity    Mean_Pos_Pred_Value    Mean_Neg_Pred_Value 
            0.37426901             0.68845501             0.37507310             0.68788290 
   Mean_Detection_Rate Mean_Balanced_Accuracy 
            0.12666667             0.53136201 
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.2

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] caret_6.0-73    ggplot2_2.2.0   lattice_0.20-34

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.8        magrittr_1.5       splines_3.3.2      MASS_7.3-45        munsell_0.4.3     
 [6] colorspace_1.3-1   foreach_1.4.3      minqa_1.2.4        stringr_1.1.0      car_2.1-4         
[11] plyr_1.8.4         tools_3.3.2        parallel_3.3.2     nnet_7.3-12        pbkrtest_0.4-6    
[16] grid_3.3.2         gtable_0.2.0       nlme_3.1-128       mgcv_1.8-15        quantreg_5.29     
[21] e1071_1.6-7        class_7.3-14       MatrixModels_0.4-1 iterators_1.0.8    lme4_1.1-12       
[26] lazyeval_0.2.0     assertthat_0.1     tibble_1.2         Matrix_1.2-7.1     nloptr_1.0.4      
[31] reshape2_1.4.2     ModelMetrics_1.1.0 codetools_0.2-15   stringi_1.1.2      scales_0.4.1      
[36] stats4_3.3.2       SparseM_1.74  
```

**Comment by RobertKomara** [comment]
Hi! I just noticed this problem after updating Caret yesterday. Please excuse me if I am breaking etiquette, this is my first inquiry on GitHub. Running these commands:

 ctrl <- trainControl(method = "repeatedcv",
                      number = 10,		
                      repeats = 5,               
                      summaryFunction=multiClassSummary,
                      classProbs=TRUE,
                      #selectionFunction = "tolerance",
                      allowParallel = TRUE)

xgbt.tune <- train(IsB2B~., data=md.train,  method='xgbTree', metric='Kappa', trControl=ctrl)

results in this error:

**Error in vector(type, length) : 
  vector: cannot make a vector of mode 'NULL'.**

when the code was function perfectly fine before the update. Is this a problem for Caret in general or just with specific models such as xgbTree?

Cheers!

**Comment by topepo** [comment]
It is most likely a general thing. I'll work on it today. 

Did you install from github?

**Comment by RobertKomara** [comment]
I pulled it from CRAN. Would it be useful to you for me to try the dev version on github?

**Comment by topepo** [comment]
Thanks but no; I can reproduce it with that version.

**Comment by topepo** [comment]
I synced and the problem resolved. It turns out that it was fixed in issue #528 and I forgot about it.

**Comment by RobertKomara** [comment]
Sorry to bother you again. This still seems to not be working. The last version that this worked with was 6.0-71. I tried all others greater than that (except 6.0-74 if there was one) including 6.0-75 and they failed the following test. I thought it may have been because I was using MS Open R, but I downloaded and installed R 3.3.2 and tried the same as well and had the same problems. Do you have any ideas?

> library(caret)
Loading required package: lattice
Loading required package: ggplot2
> set.seed(1)
> dat <- twoClassSim(100)
> X <- dat[,1:5]
> y <- dat[["Class"]]
> 
> model_class <- train(
+   X, y, , method='xgbTree',
+   metric='Kappa',
+   trControl=trainControl(
+     method="cv", 
+     number=5,
+     classProbs=TRUE, 
+     summaryFunction=multiClassSummary,
+     savePredictions="final")
+ )
Loading required package: xgboost
Loading required package: plyr
Error in vector(type, length) : 
  vector: cannot make a vector of mode 'NULL'.
> 
> print(model_class)
Error in print(model_class) : object 'model_class' not found
> 
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] plyr_1.8.4           xgboost_0.4-4        caret_6.0-75         ggplot2_2.1.0        lattice_0.20-34      RevoUtilsMath_10.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7        magrittr_1.5       splines_3.3.2      MASS_7.3-45        munsell_0.4.3      colorspace_1.2-7  
 [7] foreach_1.4.3      minqa_1.2.4        stringr_1.1.0      car_2.1-3          tools_3.3.2        nnet_7.3-12       
[13] pbkrtest_0.4-6     parallel_3.3.2     grid_3.3.2         data.table_1.9.6   gtable_0.2.0       nlme_3.1-128      
[19] mgcv_1.8-15        quantreg_5.29      e1071_1.6-7        class_7.3-14       MatrixModels_0.4-1 iterators_1.0.8   
[25] lme4_1.1-12        Matrix_1.2-7.1     nloptr_1.0.4       reshape2_1.4.2     ModelMetrics_1.1.0 codetools_0.2-15  
[31] stringi_1.1.2      compiler_3.3.2     RevoUtils_10.0.2   scales_0.4.0       stats4_3.3.2       SparseM_1.72      
[37] chron_2.3-47

**Comment by RobertKomara** [comment]
Sorry, but this seems to still not be working. I installed a fresh copy of 6.0-75 just now and ran the following tests. The last version that seems to work for this is 6.0-71:

Caret Test
================

Running Caret 6.0-71
--------------------

``` r
library(caret)
```

    ## Loading required package: lattice

    ## Loading required package: ggplot2

``` r
set.seed(1)
dat <- twoClassSim(100)
X <- dat[,1:5]
y <- dat[["Class"]]

model_class <- train(
  X, y, method='xgbTree',
  metric='Kappa',
  trControl=trainControl(
    method="cv", 
    number=5,
    classProbs=TRUE, 
    summaryFunction=multiClassSummary)
)
```

    ## Loading required package: xgboost

    ## Loading required package: plyr

``` r
print(model_class)
```

    ## eXtreme Gradient Boosting 
    ## 
    ## 100 samples
    ##   5 predictor
    ##   2 classes: 'Class1', 'Class2' 
    ## 
    ## No pre-processing
    ## Resampling: Cross-Validated (5 fold) 
    ## Summary of sample sizes: 80, 80, 81, 80, 79 
    ## Resampling results across tuning parameters:
    ## 
    ##   eta  max_depth  colsample_bytree  nrounds  logLoss    ROC      
    ##   0.3  1          0.6                50      0.4687844  0.8435113
    ##   0.3  1          0.6               100      0.4919091  0.8353480
    ##   0.3  1          0.6               150      0.5061484  0.8285453
    ##   0.3  1          0.8                50      0.4699971  0.8273940
    ##   0.3  1          0.8               100      0.4815070  0.8377289
    ##   0.3  1          0.8               150      0.4927652  0.8296442
    ##   0.3  2          0.6                50      0.5146657  0.8222920
    ##   0.3  2          0.6               100      0.5500785  0.8196756
    ##   0.3  2          0.6               150      0.5853222  0.8037153
    ##   0.3  2          0.8                50      0.4685916  0.8464155
    ##   0.3  2          0.8               100      0.4993035  0.8403977
    ##   0.3  2          0.8               150      0.4957119  0.8471481
    ##   0.3  3          0.6                50      0.5344720  0.8082679
    ##   0.3  3          0.6               100      0.5715378  0.8142334
    ##   0.3  3          0.6               150      0.5851659  0.8255887
    ##   0.3  3          0.8                50      0.5058371  0.8207745
    ##   0.3  3          0.8               100      0.5388538  0.8146520
    ##   0.3  3          0.8               150      0.5548595  0.8091575
    ##   0.4  1          0.6                50      0.4754303  0.8252486
    ##   0.4  1          0.6               100      0.5015120  0.8274464
    ##   0.4  1          0.6               150      0.5146291  0.8223182
    ##   0.4  1          0.8                50      0.4828160  0.8287284
    ##   0.4  1          0.8               100      0.4898309  0.8208006
    ##   0.4  1          0.8               150      0.5022138  0.8186028
    ##   0.4  2          0.6                50      0.5085914  0.8389325
    ##   0.4  2          0.6               100      0.5578814  0.8301936
    ##   0.4  2          0.6               150      0.5749214  0.8344322
    ##   0.4  2          0.8                50      0.5150736  0.8221612
    ##   0.4  2          0.8               100      0.5750871  0.8028257
    ##   0.4  2          0.8               150      0.5904701  0.8020931
    ##   0.4  3          0.6                50      0.5141991  0.8121402
    ##   0.4  3          0.6               100      0.5798702  0.8106750
    ##   0.4  3          0.6               150      0.6018146  0.8086342
    ##   0.4  3          0.8                50      0.5236716  0.8151753
    ##   0.4  3          0.8               100      0.5289809  0.8391941
    ##   0.4  3          0.8               150      0.5319494  0.8465201
    ##   Accuracy   Kappa      Sensitivity  Specificity  Pos_Pred_Value
    ##   0.7407519  0.4195718  0.8043956    0.6142857    0.8054212     
    ##   0.7707519  0.4947856  0.8043956    0.7000000    0.8456643     
    ##   0.7507519  0.4536353  0.7890110    0.6714286    0.8277156     
    ##   0.7302757  0.3814940  0.8186813    0.5571429    0.7856410     
    ##   0.7507519  0.4434805  0.8043956    0.6428571    0.8205728     
    ##   0.7507519  0.4434805  0.8043956    0.6428571    0.8205728     
    ##   0.7507519  0.4453917  0.8043956    0.6428571    0.8176923     
    ##   0.7602757  0.4573044  0.8186813    0.6428571    0.8244689     
    ##   0.7702757  0.4771782  0.8340659    0.6428571    0.8257509     
    ##   0.7808020  0.4950716  0.8494505    0.6428571    0.8343823     
    ##   0.7712782  0.4901606  0.8197802    0.6714286    0.8371753     
    ##   0.7708020  0.4775680  0.8340659    0.6428571    0.8302156     
    ##   0.7597995  0.4538575  0.8329670    0.6142857    0.8101832     
    ##   0.7597995  0.4555951  0.8329670    0.6142857    0.8083516     
    ##   0.7897995  0.5192814  0.8637363    0.6428571    0.8259341     
    ##   0.7602757  0.4715031  0.8032967    0.6714286    0.8287646     
    ##   0.7602757  0.4701870  0.8032967    0.6714286    0.8302797     
    ##   0.7602757  0.4701870  0.8032967    0.6714286    0.8302797     
    ##   0.7502757  0.4343080  0.8186813    0.6142857    0.8110490     
    ##   0.7407519  0.4297265  0.7890110    0.6428571    0.8125641     
    ##   0.7508020  0.4515477  0.8032967    0.6428571    0.8145979     
    ##   0.7407519  0.4195718  0.8043956    0.6142857    0.8054212     
    ##   0.7407519  0.4195718  0.8043956    0.6142857    0.8054212     
    ##   0.7407519  0.4195718  0.8043956    0.6142857    0.8054212     
    ##   0.7808020  0.5007180  0.8494505    0.6428571    0.8283974     
    ##   0.7903258  0.5146565  0.8791209    0.6142857    0.8174451     
    ##   0.8003258  0.5387388  0.8791209    0.6428571    0.8315476     
    ##   0.7697995  0.4717719  0.8483516    0.6142857    0.8139927     
    ##   0.7697995  0.4796774  0.8329670    0.6428571    0.8224542     
    ##   0.7297995  0.3735037  0.8329670    0.5285714    0.7757509     
    ##   0.7902757  0.5381386  0.8186813    0.7285714    0.8595338     
    ##   0.7602757  0.4701870  0.8032967    0.6714286    0.8302797     
    ##   0.7702757  0.4888314  0.8186813    0.6714286    0.8317949     
    ##   0.7803258  0.5022752  0.8483516    0.6428571    0.8249542     
    ##   0.7703258  0.4836308  0.8329670    0.6428571    0.8234391     
    ##   0.7703258  0.4836308  0.8329670    0.6428571    0.8234391     
    ##   Neg_Pred_Value  Detection_Rate  Balanced_Accuracy
    ##   0.6289683       0.5315539       0.7093407        
    ##   0.6587302       0.5315539       0.7521978        
    ##   0.6373016       0.5215539       0.7302198        
    ##   0.6121429       0.5410777       0.6879121        
    ##   0.6373016       0.5315539       0.7236264        
    ##   0.6373016       0.5315539       0.7236264        
    ##   0.6396825       0.5315539       0.7236264        
    ##   0.6416667       0.5410777       0.7307692        
    ##   0.6630952       0.5510777       0.7384615        
    ##   0.7083333       0.5616040       0.7461538        
    ##   0.6944444       0.5420802       0.7456044        
    ##   0.6883333       0.5516040       0.7384615        
    ##   0.6607143       0.5506015       0.7236264        
    ##   0.6642857       0.5506015       0.7236264        
    ##   0.7166667       0.5706015       0.7532967        
    ##   0.6539683       0.5310777       0.7373626        
    ##   0.6511905       0.5310777       0.7373626        
    ##   0.6511905       0.5310777       0.7373626        
    ##   0.6416667       0.5410777       0.7164835        
    ##   0.6289683       0.5215539       0.7159341        
    ##   0.6789683       0.5316040       0.7230769        
    ##   0.6289683       0.5315539       0.7093407        
    ##   0.6289683       0.5315539       0.7093407        
    ##   0.6289683       0.5315539       0.7093407        
    ##   0.7200000       0.5616040       0.7461538        
    ##   0.7523810       0.5811278       0.7467033        
    ##   0.7595238       0.5811278       0.7609890        
    ##   0.6807143       0.5606015       0.7313187        
    ##   0.6714286       0.5506015       0.7379121        
    ##   0.6204762       0.5506015       0.6807692        
    ##   0.6861111       0.5410777       0.7736264        
    ##   0.6511905       0.5310777       0.7373626        
    ##   0.6678571       0.5410777       0.7450549        
    ##   0.7214286       0.5611278       0.7456044        
    ##   0.7047619       0.5511278       0.7379121        
    ##   0.7047619       0.5511278       0.7379121        
    ## 
    ## Tuning parameter 'gamma' was held constant at a value of 0
    ## 
    ## Tuning parameter 'min_child_weight' was held constant at a value of 1
    ## Kappa was used to select the optimal model using  the largest value.
    ## The final values used for the model were nrounds = 150, max_depth = 2,
    ##  eta = 0.4, gamma = 0, colsample_bytree = 0.6 and min_child_weight = 1.

``` r
sessionInfo()
```

    ## R version 3.3.2 (2016-10-31)
    ## Platform: x86_64-w64-mingw32/x64 (64-bit)
    ## Running under: Windows 10 x64 (build 10586)
    ## 
    ## locale:
    ## [1] LC_COLLATE=English_United Kingdom.1252 
    ## [2] LC_CTYPE=English_United Kingdom.1252   
    ## [3] LC_MONETARY=English_United Kingdom.1252
    ## [4] LC_NUMERIC=C                           
    ## [5] LC_TIME=English_United Kingdom.1252    
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ## [1] plyr_1.8.4           xgboost_0.4-4        caret_6.0-71        
    ## [4] ggplot2_2.1.0        lattice_0.20-34      RevoUtilsMath_10.0.0
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] Rcpp_0.12.7        compiler_3.3.2     formatR_1.4       
    ##  [4] nloptr_1.0.4       class_7.3-14       iterators_1.0.8   
    ##  [7] tools_3.3.2        digest_0.6.10      lme4_1.1-12       
    ## [10] evaluate_0.10      gtable_0.2.0       nlme_3.1-128      
    ## [13] mgcv_1.8-15        Matrix_1.2-7.1     foreach_1.4.3     
    ## [16] yaml_2.1.13        parallel_3.3.2     SparseM_1.72      
    ## [19] e1071_1.6-7        stringr_1.1.0      knitr_1.14        
    ## [22] pROC_1.8           RevoUtils_10.0.2   MatrixModels_0.4-1
    ## [25] stats4_3.3.2       rprojroot_1.1      grid_3.3.2        
    ## [28] nnet_7.3-12        data.table_1.9.6   rmarkdown_1.3     
    ## [31] minqa_1.2.4        reshape2_1.4.2     car_2.1-3         
    ## [34] magrittr_1.5       backports_1.0.4    scales_0.4.0      
    ## [37] codetools_0.2-15   htmltools_0.3.5    MASS_7.3-45       
    ## [40] splines_3.3.2      pbkrtest_0.4-6     colorspace_1.2-7  
    ## [43] quantreg_5.29      stringi_1.1.2      munsell_0.4.3     
    ## [46] chron_2.3-47

While 75 is not working:

Caret Test
================

Running Caret 6.0-75
--------------------

``` r
library(caret)
```

    ## Loading required package: lattice

    ## Loading required package: ggplot2

``` r
set.seed(1)
dat <- twoClassSim(100)
X <- dat[,1:5]
y <- dat[["Class"]]

model_class <- train(
  X, y, method='xgbTree',
  metric='Kappa',
  trControl=trainControl(
    method="cv", 
    number=5,
    classProbs=TRUE, 
    summaryFunction=multiClassSummary)
)
```

    ## Loading required package: xgboost

    ## Loading required package: plyr

    ## Error in vector(type, length): vector: cannot make a vector of mode 'NULL'.

``` r
print(model_class)
```

    ## Error in print(model_class): object 'model_class' not found

``` r
sessionInfo()
```

    ## R version 3.3.2 (2016-10-31)
    ## Platform: x86_64-w64-mingw32/x64 (64-bit)
    ## Running under: Windows 10 x64 (build 10586)
    ## 
    ## locale:
    ## [1] LC_COLLATE=English_United Kingdom.1252 
    ## [2] LC_CTYPE=English_United Kingdom.1252   
    ## [3] LC_MONETARY=English_United Kingdom.1252
    ## [4] LC_NUMERIC=C                           
    ## [5] LC_TIME=English_United Kingdom.1252    
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ## [1] plyr_1.8.4           xgboost_0.4-4        caret_6.0-75        
    ## [4] ggplot2_2.1.0        lattice_0.20-34      RevoUtilsMath_10.0.0
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] Rcpp_0.12.7        compiler_3.3.2     formatR_1.4       
    ##  [4] nloptr_1.0.4       class_7.3-14       iterators_1.0.8   
    ##  [7] tools_3.3.2        digest_0.6.10      lme4_1.1-12       
    ## [10] evaluate_0.10      nlme_3.1-128       gtable_0.2.0      
    ## [13] mgcv_1.8-15        Matrix_1.2-7.1     foreach_1.4.3     
    ## [16] yaml_2.1.13        parallel_3.3.2     SparseM_1.72      
    ## [19] e1071_1.6-7        stringr_1.1.0      knitr_1.14        
    ## [22] RevoUtils_10.0.2   MatrixModels_0.4-1 stats4_3.3.2      
    ## [25] rprojroot_1.1      grid_3.3.2         nnet_7.3-12       
    ## [28] data.table_1.9.6   rmarkdown_1.3      minqa_1.2.4       
    ## [31] reshape2_1.4.2     car_2.1-3          magrittr_1.5      
    ## [34] backports_1.0.4    scales_0.4.0       codetools_0.2-15  
    ## [37] ModelMetrics_1.1.0 htmltools_0.3.5    MASS_7.3-45       
    ## [40] splines_3.3.2      pbkrtest_0.4-6     colorspace_1.2-7  
    ## [43] quantreg_5.29      stringi_1.1.2      munsell_0.4.3     
    ## [46] chron_2.3-47

I thought this may have something to do with using Microsoft's Open R, but the same thing happens with R 3.3.2. I don't know what else to try besides that. Thanks for any help you might be able to provide.
