### ISSUE TITLE
optimismBoot error

### ISSUE THREAD

**Issue by Weekend-Warrior** [topepo/caret#706]
I'm getting an error in the nominalTrainWorkflow. .export in the foreach loop of result is looking for an object called 'optimismBoot', assigned just before the loop but no object exists. Is there a missing condition?

**Comment by topepo** [comment]
Please read the issue template. Providing a reproducible example and the results of `sessionInfo` will help get your question answered.

**Comment by Weekend-Warrior** [comment]
Sure Max, thanks. I apologize for the breach of etiquette.

**Comment by topepo** [comment]
I'm putting together a CRAN submission, so if you have an example to send, sooner is better than later.

**Comment by Alanocallaghan** [comment]
I have run into this problem, though it's not entirely reproducible. I believe it is related to the use of parallel backends.

```{r}
library(caret)
library(doParallel)
library(glmnet)


set.seed(100)

cl <- makeCluster(2)
registerDoParallel(cl)

glm_grid <- expand.grid(
        alpha = seq(0, 1, length.out=10), 
        lambda = exp(seq(log(1e-4), log(1e-1), length.out = 10)))

predictor_matrix <- matrix(rnorm(10000), ncol=200, 
    dimnames=list(NULL, paste("column", 1:200)))
labels <- factor(sample(1:0, nrow(predictor_matrix), replace=TRUE))


tctl <- trainControl(
    method = "repeatedcv",
    number = 5,
    repeats = 10,
    allowParallel = TRUE
)

fit1 <- caret::train(
    x = predictor_matrix,
    y = labels,
    method = "glmnet",
    family = "binomial",
    trControl = tctl
    # ,tuneGrid = glm_grid
)

```

**Comment by topepo** [comment]
I can reproduce it. I'll look into it.

**Comment by topepo** [comment]
That should fix the issue. Please retest and check on your system.

**Comment by Alanocallaghan** [comment]
Works fine for me now, thanks for the quick fix!

**Comment by bvvamsik** [comment]
I am still having this issue and still getting the error 
Error in e$fun(obj, substitute(ex), parent.frame(), e$data) : 
  unable to find variable "optimismBoot"

**Comment by YinanZheng** [comment]
Same problem here as @bvvamsik . Using latest 6.0.77. I also still can reproduce the problem using the @Alanocallaghan posted above.

**Comment by Alanocallaghan** [comment]
Are you guys running the github version or the CRAN version? The latest CRAN version was pushed before this was fixed.

**Comment by Triamus** [comment]
Installing from GitHub via ```devtools::install_github('topepo/caret/pkg/caret')``` solved it for me.

**Comment by bvvamsik** [comment]
"GitHub Installation" Worked perfectly for me too, hope we will get that CRAN repo update as well, which might help us while scaling our machine learning algorithms..

**Comment by garycai** [comment]
After installing `caret` from `github`, I still ran into this problem when using the `recipes` packages:

```
library(caret)
library(doParallel)
library(glmnet)
library(recipes)

set.seed(100)

cl <- makeCluster(2)
registerDoParallel(cl)

test_data <- as.data.frame(matrix(rnorm(10000), ncol=200, 
                                  dimnames=list(NULL, paste("column", 1:200))))
test_data$label <- factor(sample(1:0, nrow(test_data), replace=TRUE))

data_recipe <- recipe(label ~ ., data = test_data) %>%
    step_center(all_predictors()) %>%
    step_scale(all_predictors())

tctl <- trainControl(
    method = "repeatedcv",
    number = 5,
    repeats = 10,
    allowParallel = TRUE
)

fit1 <- caret::train(
    x = data_recipe,
    data = test_data,
    method = "glmnet",
    family = "binomial",
    trControl = tctl
)
```

Output
`
Error in e$fun(obj, substitute(ex), parent.frame(), e$data) : 
  unable to find variable "optimism_boot"
`

**Comment by tomehta** [comment]
Any idea when the fix will be committed to CRAN ? I am getting the same error while trying parallel processing with caret

**Comment by YinanZheng** [comment]
@tomehta @garycai  I am using R 3.4.2 and installing from github devtools::install_github('topepo/caret/pkg/caret') works pretty well for me... I had an impression that CRAN update will be around December.

**Comment by topepo** [comment]
I'm shooting for this week.

**Comment by caa25** [comment]
Ran into exact same problem today (11/19/17).  Triggered devtools::install_github('topepo/caret/pkg/caret').  Works like a charm.  Thanks all.

**Comment by topepo** [comment]
@tomehta @Alanocallaghan @bvvamsik 

FYI... A new version has been sent to CRAN but a problem with a reverse dependency is holding it up. I've contacted the package owner but have not heard back. I'll give it a few more days then ask them to let it through.

**Comment by mbeekink** [comment]
@topepo Thank you for solving the issue. Although the improved version is still nog available through CRAN (28/11/2017). When do you think it will be available?
